---
abstract: 'Create PDF files from Catalyst using Template Toolkit templates'
author:
  - 'Jon Allen <jj@pennysarcade.co.uk>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.150001'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catalyst-View-PDF-Reuse
no_index:
  directory:
    - t
    - inc
requires:
  Catalyst::View::TT: '0'
  File::chdir: '0'
  PDF::Reuse: '0'
  Template::Plugin::Procedural: '0'
  Test::More: '0'
  parent: '0'
version: '0.05'
